# Generated by Django 5.0.6 on 2024-09-06 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DQAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('status', models.CharField(blank=True, choices=[('Ongoing', 'O'), ('Validated', 'V')], max_length=9)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('score', models.FloatField()),
                ('rdf', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DQMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('definition', models.TextField()),
                ('additional_information', models.TextField()),
                ('measurement_approach', models.TextField()),
                ('formula', models.TextField()),
                ('weight', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='DQDimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('definition', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EHDSCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('version', models.IntegerField()),
                ('rdf', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('dq_assessment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='webapp.dqassessment')),
            ],
        ),
        migrations.CreateModel(
            name='DQCategoricalMetric',
            fields=[
                ('dqmetric_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='webapp.dqmetric')),
            ],
            bases=('webapp.dqmetric',),
        ),
        migrations.AddField(
            model_name='dqmetric',
            name='ehds_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.dqdimension'),
        ),
        migrations.CreateModel(
            name='DQMetricValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=256)),
                ('dq_assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.dqassessment')),
                ('dq_metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.dqmetric')),
            ],
        ),
        migrations.AddField(
            model_name='dqdimension',
            name='ehds_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.ehdscategory'),
        ),
        migrations.CreateModel(
            name='DQCategoricalMetricCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dq_categorical_metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.dqcategoricalmetric')),
            ],
        ),
    ]
