# Generated by Django 5.0.6 on 2024-09-06 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dqmetric',
            old_name='ehds_category',
            new_name='dq_dimension',
        ),
    ]
