# Generated by Django 5.0.6 on 2024-09-06 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_alter_dqassessment_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='dqcategoricalmetriccategory',
            name='text',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='dqcategoricalmetriccategory',
            name='value',
            field=models.IntegerField(default=0),
        ),
    ]
