# Generated by Django 5.0.6 on 2024-09-10 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_dqcategoricalmetriccategory_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dqassessment',
            name='name',
        ),
    ]
