# Generated by Django 5.0.6 on 2024-10-15 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_dataset_uri'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogue',
            name='fdp_id',
            field=models.CharField(default='', max_length=512),
        ),
    ]
