# Generated by Django 5.1 on 2024-10-25 08:51
# Generated by Django 5.0.6 on 2024-10-24 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_catalogue_fdp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogue',
            name='fdp_id',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
