# Generated by Django 5.0.6 on 2024-11-04 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0016_alter_catalogue_fdp_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaturityDimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('definition', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='catalogue',
            name='fdp_id',
        ),
        migrations.CreateModel(
            name='MaturityDimensionLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0)),
                ('text', models.TextField()),
                ('maturity_dimension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.maturitydimension')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationMaturityMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.organization')),
            ],
        ),
        migrations.CreateModel(
            name='MaturityDimensionValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=256, null=True)),
                ('maturity_dimension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.maturitydimension')),
                ('maturity_matrix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.organizationmaturitymatrix')),
            ],
        ),
    ]
