# Generated by Django 5.0.6 on 2024-11-05 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0019_alter_dataset_dq_assessment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maturitydimensionvalue',
            name='maturity_dimension',
        ),
        migrations.RemoveField(
            model_name='maturitydimensionvalue',
            name='value',
        ),
        migrations.AddField(
            model_name='maturitydimensionvalue',
            name='maturity_dimension_level',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.maturitydimensionlevel'),
        ),
    ]
