# Generated by Django 5.0.6 on 2024-11-05 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0020_remove_maturitydimensionvalue_maturity_dimension_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maturitydimensionvalue',
            name='maturity_dimension',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='webapp.maturitydimension'),
        ),
    ]
