# Generated by Django 5.0.6 on 2024-11-05 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0021_maturitydimensionvalue_maturity_dimension'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maturitydimensionvalue',
            name='maturity_matrix',
        ),
        migrations.AddField(
            model_name='maturitydimensionvalue',
            name='maturity_organization',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.organization'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='OrganizationMaturityMatrix',
        ),
    ]
